#!/bin/bash

# i am not very good with bash, but looks like its working fine
########################################################
#
#  evtest /dev/input/event6 | 4click.sh 'xdotool key super+w' | sh -
#
########################################################
#function 4click() {
IFS=" "
#while read -r line; do

#eventArray=($line)
coproc evtest /dev/input/event6;
#coproc stdbuf -oL -- evtest /dev/input/event6;
while read -u ${COPROC[0]} -a eventArray; do

    touchEvent=${eventArray[8]}
    touchValue=${eventArray[10]}
    touchTime=${eventArray[2]}

    needleEvent="(BTN_TOOL_QUADTAP),"
    #cancelEvent="(ABS_MT_POSITION_X),"

    #echo $touchValue
    xEvent="(ABS_MT_POSITION_X),"
    #can be (ABS_Y),
    yEvent="(ABS_MT_POSITION_Y),"

    #if [ x"$touchEvent" == x"$cancelEvent" ]; then
      #cancelTap=true
    #fi
    if [ "$touchEvent" == "$needleEvent" ] && [ x"$touchValue" == x"1" ]; then
    lastVal=${touchTime}
    trigger=true
    count=$((0))
    #echo correct
    fi
    if [ "$touchEvent" == "(MSC_TIMESTAMP)," ] && [ "$lastVal" == "$touchTime" ]; then
    stamp=${touchValue}
    #echo "$1"
    fi
    if [ "$trigger" == "true" ] && ([ "$touchEvent" == "(ABS_MT_POSITION_X)," ] || [ "$touchEvent" == "(ABS_MT_POSITION_Y)," ]); then
      count=$((count + 1))
    fi
    if [ "$touchEvent" == "$needleEvent" ] && [ x"$touchValue" == x"0" ]; then
    currentVal=${touchTime}
    #echo correct
    fi
    #if [ "$touchEvent" == "(MSC_TIMESTAMP)," ] && [ "$currentVal" == "$touchTime" ]; then
    if [ "$touchEvent" == "(MSC_TIMESTAMP)," ] && [ "$currentVal" == "$touchTime" ] && [ $((touchValue - stamp)) -lt 500000 ] && [ $((touchValue - stamp)) -gt 7200 ] ; then
    #if [ "$touchEvent" == "(MSC_TIMESTAMP)," ] && [ "$currentVal" == "$touchTime" ] && [ $touchValue -lt 750000 ]; then
      trigger=false
      #echo $count
      if [ $count -lt 28 ]; then
       #echo $count
       #echo $((touchValue - stamp))
       #echo "$1"
       xdotool key super+w
     fi
    fi

#then
  #tapTime=${touchTime##*.}
  #if [ x"$touchValue" == x"0" ]; then # fingersUp
    #if ! $cancelTap; then
      #echo "$1"
#echo correct
    #fi
  #fi
  #if [ x"$touchValue" == x"1" ]; then # fingersDOWN
  #   cancelTap=false
  #fi
#fi
done
#}

#evtest /dev/input/event6 | 4click "xdotool key super+w" | sh & disown
