#!/bin/bash
if [[ -n "$1" ]]; then
    libinput-gestures-setup restart;
    pkill -f "python3.*4fingertap*";
    4fingertap & disown;
    4fingertap_external & disown;
    #pkill pend;
    #pend; //using gnome keyboard shortcut module with XmodMap
else
  daemonize "$0" execute
fi
